// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wikaakudfwjpecqiizck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indpa2Fha3VkZndqcGVjcWlpemNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0ODIzNzMsImV4cCI6MjA3MjA1ODM3M30.1ofPNyKZXpoFyCRFPADnvZhkX8OEIH76TyZ2W0lQB0E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});